services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=zachnoble1993+letsencrypt@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gamelib
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${GAMELIBRARY_DB_PASSWORD}
      - POSTGRES_USER=${GAMELIBRARY_DB_USERNAME}
      - POSTGRES_DB=${GAMELIBRARY_DB}
    networks:
      - gamelib
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create-db.sql
  gamelib:
    image: ghcr.io/distractedpen/gamelib:prod
    environment:
      - GAMELIBRARY_DB_USERNAME=${GAMELIBRARY_DB_USERNAME}
      - GAMELIBRARY_DB_PASSWORD=${GAMELIBRARY_DB_PASSWORD}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - gamelib
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamelib.rule=Host(`gamelib.cloud`)"
      - "traefik.http.routers.gamelib.entrypoints=websecure"
      - "traefik.http.routers.gamelib.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3

networks:
  gamelib:
    driver: bridge

volumes:
  postgres-data:
  letsencrypt: