services:
  reverse-proxy:
    image: traefik:v3.3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # HTTP PORT
      - "80:80"
      # WEB UI
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${GAMELIBRARY_DB_PASSWORD}
      - POSTGRES_USER=${GAMELIBRARY_DB_USERNAME}
      - POSTGRES_DB=${GAMELIBRARY_DB}
    networks:
      - gamelib
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create-db.sql
  jar:
    build: .
    environment:
      - GAMELIBRARY_DB_USERNAME=${GAMELIBRARY_DB_USERNAME}
      - GAMELIBRARY_DB_PASSWORD=${GAMELIBRARY_DB_PASSWORD}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - gamelib

networks:
  gamelib:
    driver: bridge

volumes:
  postgres-data: