services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${GAMELIBRARY_DB_PASSWORD}
      - POSTGRES_USER=${GAMELIBRARY_DB_USERNAME}
      - POSTGRES_DB=${GAMELIBRARY_DB}
    ports:
      - "5432:5432"
    networks:
      - gamelib
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create-db.sql
  jar:
    build: .
    environment:
      - GAMELIBRARY_DB_USERNAME=${GAMELIBRARY_DB_USERNAME}
      - GAMELIBRARY_DB_PASSWORD=${GAMELIBRARY_DB_PASSWORD}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - gamelib

networks:
  gamelib:
    driver: bridge

volumes:
  postgres-data: